eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
  
spring:
  application:
    name: eshop-price-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.91.142:3306/eshop?charsetEncoding=utf8
    username: root
    password: root
    
    